@startuml
!theme plain
'skinparam defaultFontColor purple
skinparam roundCorner 8
rectangle "URLS\n(urls.py)" as U
circle "Requête\nHTTP" as RQ
circle "Réponse\nHTTP\n(html)" as RS
rectangle "MODÈLE\n(models.py)" as M
rectangle "VUE\n(views.py)" as V
rectangle "GABARIT\n(<fichier>.html)" as T
RQ -> U
U -d-> V : Redirection vers\nla vue appropriée
M <-> V : Lecture/écriture\ndes données
T -u-> V
V -> RS
caption Architecture **MVT**
footer "Application Django"
@enduml
